default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.8
    hooks:
      - id: docformatter
        name: docformatter
        additional_dependencies: [tomli]
        args:
          - --in-place
          - --config
          - ./pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
      - id: ruff-format

  # - repo: https://github.com/rbubley/mirrors-prettier
  #   # fork of oficial repo which support is discontinued
  #   rev: v3.8.3
  #   hooks:
  #     - id: prettier
  #       types_or: [markdown, yaml, json, toml]
  #       additional_dependencies:
  #         - prettier@3.6.2
  #         - prettier-plugin-toml@2.0.6
  #         # for plugings see https://prettier.io/docs/plugins#community-plugins
  #       args: [--print-width=80, --prose-wrap=always]

  - repo: local
    hooks:
      - id: dprint
        name: dprint format
        language: rust
        entry: dprint fmt
        additional_dependencies:
          - "cli:dprint:0.54.0"
        types_or: [markdown, json, yaml, toml, dockerfile]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.1.0
    hooks:
      - id: sqlfluff-lint
      # Enable later if you trust automatic SQL rewrites:
      # - id: sqlfluff-fix

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
